---
abstract: 'manipulate SRT subtitle files'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Video-Subtitle-SRT
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006001
resources:
  bugtracker: https://github.com/benkasminbullock/Video-Subtitle-SRT/issues
  repository: https://github.com/benkasminbullock/Video-Subtitle-SRT
version: 0.05
